/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Api Books */
        get: operations["read_api_books_api_books_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/volumes/brief/{key_type}/{value}.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Api Volumes Brief */
        get: operations["read_api_volumes_brief_api_volumes_brief__key_type___value__json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/authors/{olid}.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Authors */
        get: operations["read_authors_authors__olid__json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/authors/{olid}/works.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Authors Works */
        get: operations["read_authors_works_authors__olid__works_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/{olid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Books */
        get: operations["read_books_books__olid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/covers/{key_type}/{value}-{size}.jpg": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Covers Key Type Value Size Jpeg */
        get: operations["read_covers_key_type_value_size_jpeg_covers__key_type___value___size__jpg_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/isbn/{isbn}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Isbn */
        get: operations["read_isbn_isbn__isbn__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Search Json */
        get: operations["read_search_json_search_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/authors.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Search Authors Json */
        get: operations["read_search_authors_json_search_authors_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects/{subject}.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Subjects */
        get: operations["read_subjects_subjects__subject__json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/works/{olid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Works */
        get: operations["read_works_works__olid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            detail: components["schemas"]["ValidationError"][];
        };
        /** ValidationError */
        ValidationError: {
            loc: string[];
            msg: string;
            type: string;
        };
        /** SearchResultResponse */
        SearchResultResponse: {
            docs?: components["schemas"]["BookData"][];
            documentation_url?: string;
            numFound?: number;
            numFoundExact?: boolean;
            num_found?: number;
            offset?: number;
            q?: string;
            start?: number;
        };
        /** SearchResultData */
        BookData: {
            key?: string;
            redirects?: string[];
            title?: string;
            subtitle?: string;
            alternative_title?: string;
            alternative_subtitle?: string;
            cover_i?: number;
            ebook_access?: string;
            edition_count?: number;
            edition_key?: string[];
            format?: string[];
            by_statement?: string;
            publish_date?: string;
            lccn?: string[];
            ia?: string[];
            oclc?: string[];
            isbn?: string[];
            contributor?: string[];
            publish_place?: string;
            publisher?: string;
            first_sentence?: string;
            author_key?: string[];
            author_name?: string[];
            author_alternative_name?: string[];
            subject?: string[];
            person?: string[];
            place?: string[];
            time?: string[];
            has_fulltext?: boolean;
            title_suggest?: string;
            publish_year?: number;
            language?: string[];
            number_of_pages_median?: number;
            ia_count?: number;
            publisher_facet?: string[];
            author_facet?: string[];
            first_publish_year?: number;
            ratings_count?: number;
            readinglog_count?: number;
            want_to_read_count?: number;
            currently_reading_count?: number;
            already_read_count?: number;
            subject_key?: string[];
            person_key?: string[];
            place_key?: string[];
            time_key?: string[];
            lcc?: string[];
            ddc?: string[];
            lcc_sort?: string;
            ddc_sort?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_api_books_api_books_get: {
        parameters: {
            query: {
                bibkeys: string;
                /** @description Specifies the response format. Possible values are json and javascript. When not specified the format is javascript. */
                format?: string;
                /** @description The name of the JavaScript function to call with the result. This is considered only when the format is javascript. */
                callback?: unknown;
                /** @description Decides what information to provide for each matched bib_key. Possible values are viewapi and data. The default value is viewapi. */
                jscmd?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_api_volumes_brief_api_volumes_brief__key_type___value__json_get: {
        parameters: {
            query?: {
                callback?: unknown;
            };
            header?: never;
            path: {
                key_type: unknown;
                value: unknown;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_authors_authors__olid__json_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                olid: unknown;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_authors_works_authors__olid__works_json_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                olid: unknown;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_books_books__olid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                olid: unknown;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_covers_key_type_value_size_jpeg_covers__key_type___value___size__jpg_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_type: unknown;
                value: unknown;
                size: unknown;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_isbn_isbn__isbn__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                isbn: unknown;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_search_json_search_json_get: {
        parameters: {
            query: {
                q: unknown;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_search_authors_json_search_authors_json_get: {
        parameters: {
            query: {
                q: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_subjects_subjects__subject__json_get: {
        parameters: {
            query?: {
                details?: boolean;
            };
            header?: never;
            path: {
                subject: unknown;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_works_works__olid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                olid: unknown;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
